---
- name: Ensure pip3 is installed.
  package:
    name: python3-pip
    state: present

- name: Ensure pip_install are installed.
  pip:
    name: "{{ item.name | default(item) }}"
    extra_args: "{{ item.extra_args | default(omit) }}"
    executable: pip3
  with_items: "{{ pip_install }}"
